language: cpp
dist: xenial

os: linux

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake-data
      - cmake
      - gcc-8
      - g++-8
      - clang-6.0

script:
  - "cmake ."
  - "make"
  - "./malix ./tests.malix"