language: cpp
dist: xenial

os: linux

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - gcc-8
      - g++-8
      - clang-6.0
      - boost1.67

script:
  - "cmake ."
  - "make"
  - "./malix ./tests.malix"