language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake-data
      - cmake

script:
  - "cmake ."
  - "make"
  - "./malix ./tests/print.malix"
  - "./malix ./tests/variables.malix"
  - "./malix ./tests/arithmetic.malix"
  - "./malix ./tests/conditional.malix"
  - "./malix ./tests/loops.malix"
  - "./malix ./tests/functions.malix"
  - "./malix ./tests/math.malix"
  - "./malix ./tests/package.malix"