environment:
  matrix:
    - platform: MinGW
      language: cpp
      image: Visual Studio 2017

build_script:
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - md build
  - cd build
  - cmake -G "MinGW Makefiles" ..
  - cmake --build . --config Release