environment:
  matrix:
    - platform: MinGW
      language: cpp
      image: Visual Studio 2017

build_script:
  - set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin;%PATH:C:\Program Files\Git\usr\bin;=%
  - md build
  - cd build
  - cmake -G "MinGW Makefiles" -DBOOST_ROOT=C:\Libraries\boost_1_69_0 -DBOOST_LIBRARYDIR=C:\Libraries\boost_1_69_0\lib64-msvc-14.0 ..
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  - ".\\build\\malix.exe .\\tests.malix"