environment:
  matrix:
    - VS: Visual Studio 12 2013
    - VS: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS: Visual Studio 15 2017

build_script:
  - md build
  - cd build
  - cmake -G "%VS%" ..
  - cmake --build . --config Release
  - "./Release/malix.exe ../tests/print.malix"
  - "./Release/malix.exe ../tests/variables.malix"
  - "./Release/malix.exe ../tests/arithmetic.malix"
  - "./Release/malix.exe ../tests/conditional.malix"
  - "./Release/malix.exe ../tests/loops.malix"
  - "./Release/malix.exe ../tests/functions.malix"
  - "./Release/malix.exe ../tests/math.malix"
  - "./Release/malix.exe ../tests/package.malix"
