environment:
  matrix:
    - platform: MinGW
      language: cpp
      image: Visual Studio 2015

build_script:
  - md build
  - cd build
  - cmake -G "MinGW Makefiles" ..
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  - ".\\build\\Release\\malix.exe .\\tests.malix"
