environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS: Visual Studio 15 2017

build_script:
  - md build
  - cd build
  - cmake -G "%VS%" ..
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  - ".\\build\\Release\\malix.exe .\\tests.malix"
