version: "{branch}-ci-{build}"
os: Visual Studio 2015

environment:
  matrix:
    - MINGW_ARCH: x86_64
      MINGW_ROOT: C:\msys64\mingw64
      BOOST_ROOT: C:\msys64\mingw64
      BOOST_LIBRARYDIR: C:\msys64\mingw64\lib
      BOOST_INCLUDEDIR: C:\msys64\mingw64\include\boost
      CMAKE_GENERATOR: 'MSYS Makefiles'

install:
  - if defined MINGW_ROOT set PATH=%MINGW_ROOT%\bin;C:\msys64\usr\bin\;%PATH%
  - if defined MINGW_ARCH bash -lc "pacman --needed --noconfirm -S mingw-w64-%MINGW_ARCH%-boost"

build_script:
  - md build
  - cd build
  - cmake -G "%CMAKE_GENERATOR%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  - ".\\build\\malix.exe .\\tests.malix"

artifacts:
  - path: ".\\build\\malix.exe"
    name: "malix.exe"
