environment:
  matrix:
    - VS: Visual Studio 12 2013
    - VS: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VS: Visual Studio 15 2017

build_script:
  - md build
  - cd build
  - cmake -G "%VS%" ..
  - cmake --build . --config Release
  - cd %APPVEYOR_BUILD_FOLDER%
  - ".\build\Release\malix.exe .\tests\print.malix"
  - ".\build\Release\malix.exe .\tests\variables.malix"
  - ".\build\Release\malix.exe .\tests\arithmetic.malix"
  - ".\build\Release\malix.exe .\tests/conditional.malix"
  - ".\build\Release\malix.exe .\tests\loops.malix"
  - ".\build\Release\malix.exe .\tests\functions.malix"
  - ".\build\Release\malix.exe .\tests\math.malix"
  - ".\build\Release\malix.exe .\tests\package.malix"
