#ifndef MALIX_STDFUNCTIONS_H
#define MALIX_STDFUNCTIONS_H

#include "../NativeFunction.h"

MALIX_NATIVE_FUNCTION(std_isArray);
MALIX_NATIVE_FUNCTION(std_isBool);
MALIX_NATIVE_FUNCTION(std_isNil);
MALIX_NATIVE_FUNCTION(std_isNumber);
MALIX_NATIVE_FUNCTION(std_isString);
MALIX_NATIVE_FUNCTION(std_isPointer);

MALIX_NATIVE_FUNCTION(std_rand);
MALIX_NATIVE_FUNCTION(std_srand);
MALIX_NATIVE_FUNCTION(std_exit);
MALIX_NATIVE_FUNCTION(std_getenv);
MALIX_NATIVE_FUNCTION(std_system);

#endif //MALIX_STDFUNCTIONS_H
